In [2]:
import pandas
dfs = pandas.read_html('http://rate.bot.com.tw/xrt?Lang=zh-TW')
currency = dfs[0]
currency = currency.ix[:,0:5]
currency.columns = [u'幣別', u'現金匯率-本行買入', u'現金匯率-本行賣出', u'即期匯率-本行買入', u'即期匯率-本行賣出' ]
currency[u'幣別'] = currency[u'幣別'].str.extract('\((\w+)\)')
currency

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0   USD    31.665    32.207    31.965    32.065
1   HKD     3.974     4.169     4.094     4.154
2   GBP     38.52     40.45     39.39     39.81
3   AUD     22.84      23.5     23.03     23.26
4   CAD     23.46      24.2     23.73     23.95
5   SGD      21.6     22.38     22.02      22.2
6   CHF     30.51     31.57     31.04     31.33
7   JPY    0.2638    0.2748    0.2702    0.2742
8   ZAR         -         -      2.25      2.33
9   SEK      3.09       3.6      3.43      3.53
10  NZD      21.8     22.43     22.04     22.24
11  THB    0.7853    0.9283    0.8738    0.9138
12  PHP    0.5914    0.7244         -         -
13  IDR   0.00208   0.00278         -         -
14  EUR     32.72     33.87     33.22     33.62
15  KRW   0.02494   0.02884         -         -
16  VND   0.00103   0.00153         -         -
17  MYR     6.064     7.664         -         -
18  CNY     4.514     4.676     4.586     4.636

In [4]:
currency['Date'] = '123'
currency

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出 Date
0   USD    31.665    32.207    31.965    32.065  123
1   HKD     3.974     4.169     4.094     4.154  123
2   GBP     38.52     40.45     39.39     39.81  123
3   AUD     22.84      23.5     23.03     23.26  123
4   CAD     23.46      24.2     23.73     23.95  123
5   SGD      21.6     22.38     22.02      22.2  123
6   CHF     30.51     31.57     31.04     31.33  123
7   JPY    0.2638    0.2748    0.2702    0.2742  123
8   ZAR         -         -      2.25      2.33  123
9   SEK      3.09       3.6      3.43      3.53  123
10  NZD      21.8     22.43     22.04     22.24  123
11  THB    0.7853    0.9283    0.8738    0.9138  123
12  PHP    0.5914    0.7244         -         -  123
13  IDR   0.00208   0.00278         -         -  123
14  EUR     32.72     33.87     33.22     33.62  123
15  KRW   0.02494   0.02884         -         -  123
16  VND   0.00103   0.00153         -         -  123
17  MYR     6.064     7.664         -         -  123
18  CNY     4.514     4.676     4.586     4.636  123

In [7]:
from datetime import datetime
currency['Date'] = datetime.now().strftime('%Y-%m-%d')
currency

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出        Date
0   USD    31.665    32.207    31.965    32.065  2016-12-22
1   HKD     3.974     4.169     4.094     4.154  2016-12-22
2   GBP     38.52     40.45     39.39     39.81  2016-12-22
3   AUD     22.84      23.5     23.03     23.26  2016-12-22
4   CAD     23.46      24.2     23.73     23.95  2016-12-22
5   SGD      21.6     22.38     22.02      22.2  2016-12-22
6   CHF     30.51     31.57     31.04     31.33  2016-12-22
7   JPY    0.2638    0.2748    0.2702    0.2742  2016-12-22
8   ZAR         -         -      2.25      2.33  2016-12-22
9   SEK      3.09       3.6      3.43      3.53  2016-12-22
10  NZD      21.8     22.43     22.04     22.24  2016-12-22
11  THB    0.7853    0.9283    0.8738    0.9138  2016-12-22
12  PHP    0.5914    0.7244         -         -  2016-12-22
13  IDR   0.00208   0.00278         -         -  2016-12-22
14  EUR     32.72     33.87     33.22     33.62  2016-12-22
15  KRW   0.02494   0.02884         -         -  2016-12-22
16  VND   0.00103   0.00153         -         -  2016-12-22
17  MYR     6.064     7.664         -         -  2016-12-22
18  CNY     4.514     4.676     4.586     4.636  2016-12-22

In [10]:
currency['Date'] = pandas.to_datetime(currency['Date'])
currency

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出       Date
0   USD    31.665    32.207    31.965    32.065 2016-12-22
1   HKD     3.974     4.169     4.094     4.154 2016-12-22
2   GBP     38.52     40.45     39.39     39.81 2016-12-22
3   AUD     22.84      23.5     23.03     23.26 2016-12-22
4   CAD     23.46      24.2     23.73     23.95 2016-12-22
5   SGD      21.6     22.38     22.02      22.2 2016-12-22
6   CHF     30.51     31.57     31.04     31.33 2016-12-22
7   JPY    0.2638    0.2748    0.2702    0.2742 2016-12-22
8   ZAR         -         -      2.25      2.33 2016-12-22
9   SEK      3.09       3.6      3.43      3.53 2016-12-22
10  NZD      21.8     22.43     22.04     22.24 2016-12-22
11  THB    0.7853    0.9283    0.8738    0.9138 2016-12-22
12  PHP    0.5914    0.7244         -         - 2016-12-22
13  IDR   0.00208   0.00278         -         - 2016-12-22
14  EUR     32.72     33.87     33.22     33.62 2016-12-22
15  KRW   0.02494   0.02884         -         - 2016-12-22
16  VND   0.00103   0.00153         -         - 2016-12-22
17  MYR     6.064     7.664         -         - 2016-12-22
18  CNY     4.514     4.676     4.586     4.636 2016-12-22

In [11]:
currency.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19 entries, 0 to 18
Data columns (total 6 columns):
幣別           19 non-null object
現金匯率-本行買入    19 non-null object
現金匯率-本行賣出    19 non-null object
即期匯率-本行買入    19 non-null object
即期匯率-本行賣出    19 non-null object
Date         19 non-null datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.0+ KB

In [12]:
import sqlite3
with sqlite3.connect('currency.sqlite') as db:
    currency.to_sql('currency', con = db, if_exists='append')

In [13]:
with sqlite3.connect('currency.sqlite') as db:
    df = pandas.read_sql_query('select * from currency', con = db)

In [14]:
df

    index   幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出                 Date
0       0  USD    31.665    32.207    31.965    32.065  2016-12-22 00:00:00
1       1  HKD     3.974     4.169     4.094     4.154  2016-12-22 00:00:00
2       2  GBP     38.52     40.45     39.39     39.81  2016-12-22 00:00:00
3       3  AUD     22.84      23.5     23.03     23.26  2016-12-22 00:00:00
4       4  CAD     23.46      24.2     23.73     23.95  2016-12-22 00:00:00
5       5  SGD      21.6     22.38     22.02      22.2  2016-12-22 00:00:00
6       6  CHF     30.51     31.57     31.04     31.33  2016-12-22 00:00:00
7       7  JPY    0.2638    0.2748    0.2702    0.2742  2016-12-22 00:00:00
8       8  ZAR         -         -      2.25      2.33  2016-12-22 00:00:00
9       9  SEK      3.09       3.6      3.43      3.53  2016-12-22 00:00:00
10     10  NZD      21.8     22.43     22.04     22.24  2016-12-22 00:00:00
11     11  THB    0.7853    0.9283    0.8738    0.9138  2016-12-22 00:00:00
12     12  PHP    0.5914    0.7244         -         -  2016-12-22 00:00:00
13     13  IDR   0.00208   0.00278         -         -  2016-12-22 00:00:00
14     14  EUR     32.72     33.87     33.22     33.62  2016-12-22 00:00:00
15     15  KRW   0.02494   0.02884         -         -  2016-12-22 00:00:00
16     16  VND   0.00103   0.00153         -         -  2016-12-22 00:00:00
17     17  MYR     6.064     7.664         -         -  2016-12-22 00:00:00
18     18  CNY     4.514     4.676     4.586     4.636  2016-12-22 00:00:00